// Define the hosts, to which headers  will be changed
var requestFilter = {urls: ["*://*.facebook.com/*", "*://*.facebook.net/*", "*://*.fbstatic-a.akamaihd.net/*"]};

//Define constants
var extraInfoSpec = ['requestHeaders','blocking'];

//Define function to generate js_datr cookie paramtetrised by length
function jsdatrGen (cookielength) {
  //Define text variable as string
  var text = "";
  //Define det of characters to generate js_datr cookie
  var charset = "_ABCDEFDHIJKLM_NOPQRSTUVWXYZ_abcdefghijklm_nopqrstuvwxyz_0123456789_";
  //Cookie generator 
  for (var i=0; i < cookielength; i++) {
    text += charset.charAt(Math.floor(Math.random() * charset.length));
  };
  return text;
};


//Define handler function to replace headers, parametrised by det
handler = function (details) {

//Define array of User Agets 
var uaArray = ['Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36', 
              'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36', 
              'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36w', 
              'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36', 
              'Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0','Mozilla/5.0 (Windows NT 6.1; WOW64; rv:29.0) Gecko/20120101 Firefox/29.0',
              'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/29.0',
              'Mozilla/5.0 (X11; OpenBSD amd64; rv:28.0) Gecko/20100101 Firefox/28.0',
              'Mozilla/5.0 (X11; Linux x86_64; rv:28.0) Gecko/20100101 Firefox/28.0',
              'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36',
              'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36',
              'Opera/9.80 (X11; Linux i686; Ubuntu/14.10) Presto/2.12.388 Version/12.16',
              'Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14',
              'Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14',
              'Opera/12.0 (Windows NT 5.2;U;en)Presto/22.9.168 Version/12.00',
              'Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; de) Presto/2.9.168 Version/11.52',
              'Opera/9.80 (X11; Linux x86_64; U; fr) Presto/2.9.168 Version/11.50',
              'Mozilla/5.0 (X11; Linux x86_64; rv:24.0) Gecko/20140429 Firefox/24.0 Iceweasel/24.5.0',
              'Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko',
              'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko',
              'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A',
              'Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5355d Safari/8536.25',
              'Opera/12.02 (Android 4.1; Linux; Opera Mobi/ADR-1111101157; U; en-US) Presto/2.9.201 Version/12.02',
              'Mozilla/5.0 (BlackBerry; U; BlackBerry 9900; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.346 Mobile Safari/534.11+',
              'Mozilla/5.0 (BlackBerry; U; BlackBerry 9860; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.254 Mobile Safari/534.11+',
              'Mozilla/5.0 (BlackBerry; U; BlackBerry 9850; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.254 Mobile Safari/534.11+',
              'Mozilla/5.0 (X11; Linux) KHTML/4.9.1 (like Gecko) Konqueror/4.9',
              'Mozilla/5.0 (X11; Linux 3.5.4-1-ARCH i686; es) KHTML/4.9.1 (like Gecko) Konqueror/4.9',
];

  //Define headers
  var headers = details.requestHeaders;
  //Define object of response
  var blockingResponse = {};

  /*Create loop to replace headers; Use-Agent picked up randomly from uaArray; Cookie is a sum of strings: js_datr generated by
  jsdatrGen function and the two others (constant) given by Facebook;  Referer is replaced by https://facebook.com URL */
  for (var i = 0, l = headers.length; i < l; ++i) {
        if (headers[i].name == "User-Agent") {
            headers[i].value = uaArray[Math.floor(Math.random() * (uaArray.length + 1))];
      } else if (headers[i].name == "Cookie" ) {
                headers[i].value = "_js_datr = " + jsdatrGen(24) + "; _js_reg_fb_ref=https%3A%2F%2Fwww.facebook.com%2F; _js_reg_fb_gate=https%3A%2F%2Fwww.facebook.com%2F";
      } else if (headers[i].name == "Referer" ) {
                headers[i].value = "https://www.facebook.com ";
      }
      }

  blockingResponse.requestHeaders = headers;
  return blockingResponse;
};

//Apply logic into extension by adding Listener 
chrome.webRequest.onBeforeSendHeaders.addListener(handler, requestFilter, extraInfoSpec); 
